### ISSUE TITLE
Windower crash

### ISSUE THREAD

**Issue by Saeyent** [Windower/packages#108] opened 2018-07-14 06:23 UTC
Link to crash dump. https://pastebin.com/7mu5jgbZ
Windower was running for 25 hours, 30ish minutes. Crashed immediately after doing a Unity NM. Not sure that is relevant.
Reporting as per Iryoku

**Comment by z16** [comment] 2018-07-14 06:29
The problem is this is only a log of the crash event not a proper crash dump. Which is not your fault, because this crash happens inside of our crash handler ;)

I opened an issue for that (#109). Once that is fixed we will need you to provide a proper crash dump, but not much you can do before then.

**Comment by Saeyent** [comment] 2018-07-14 06:39
[Crash dump.zip](https://github.com/Windower/packages/files/2194717/Crash.dump.zip)

This may be of use. Found in the location referenced by the crash dump/

**Comment by z16** [comment] 2018-07-14 07:42
That's more like it :D Though I'm not sure it's from that particular crash. At least the file name doesn't match what the crash handler seems to be looking for... then again, that could explain the crash. Either way, thanks for reporting this, that should help.

**Comment by alphaONE2** [comment] 2018-07-14 18:16
This looks like it's related to the packet handling code in core, but it's not clear exactly what's wrong. In fact there's nothing related to core on the stack from what I can see, but there is a call to ws2_32.dll!select(), which is what makes me think it's packet related. I'll probably need some more crash dumps to figure this out.

I've fixed the bug with the crash reporter, but I won't have time to push it out for a bit.

**Comment by Saeyent** [comment] 2018-07-21 17:53
[2018-07-21T17-39-35-9738211Z.zip](https://github.com/Windower/packages/files/2216372/2018-07-21T17-39-35-9738211Z.zip)
Additional crash, this time trying to inspect the table in 'memory.entities'.

Crash dump is similar in size to last crash dump, but may not be related to the original issue.

Steps to reproduce:
Log in.
Use @z16 's "v" utility to inspect 'memory.entities'

**Comment by z16** [comment] 2020-03-14 16:55
Closing, since everything has changed so much that it may or may not be resolved. Feel free to reopen it if the same issue persists.

**Closed by z16** 2020-03-14 16:55 UTC
Labels: category:bug
