### ISSUE TITLE
seriously when is the root of this getting fixed im sick of using windower 4

### ISSUE THREAD

**Issue by Nekseus** [Windower/packages#336] opened 2020-01-28 04:10 UTC
https://github.com/Windower/packages/blob/20841975e77e59ab50d4224d223721cc7f55c6df/packet_service/types.lua#L617

**Comment by Nekseus** [comment] 2020-01-28 04:11
its been over 6 months

**Comment by RubenatorX** [comment] 2020-01-28 04:33
No one is stopping you from fixing it

**Comment by Nekseus** [comment] 2020-01-28 05:30
its a source problem. i dont have source access no more. 😄

**Comment by Nekseus** [comment] 2020-01-28 05:31
arcon kicked me out for having opinions and talking back to ashita users slandering windower so yeah i dont have access ot the source repo no more. lol

**Comment by Nekseus** [comment] 2020-01-28 05:39
I know your an expert so i figured id fill you in on the facts 😉

**Comment by z16** [comment] 2020-01-28 06:20
Can't say when it will be fixed. Closing as it's a duplicate of #333.

**Closed by z16** 2020-01-28 06:20 UTC
